#if !canImport(ObjectiveC)
import XCTest

extension SQLKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SQLKitTests = [
        ("testBenchmarker", testBenchmarker),
        ("testColumnConstraints", testColumnConstraints),
        ("testCompositePrimaryKeyTableConstraint", testCompositePrimaryKeyTableConstraint),
        ("testCompositeUniqueTableConstraint", testCompositeUniqueTableConstraint),
        ("testDefaultColumnConstraintVariants", testDefaultColumnConstraintVariants),
        ("testForeignKeyColumnConstraintVariants", testForeignKeyColumnConstraintVariants),
        ("testGroupByHaving", testGroupByHaving),
        ("testIfExists", testIfExists),
        ("testLockingClause_forUpdate", testLockingClause_forUpdate),
        ("testLockingClause_lockInShareMode", testLockingClause_lockInShareMode),
        ("testMultipleColumnConstraintsPerRow", testMultipleColumnConstraintsPerRow),
        ("testPrimaryKeyColumnConstraintVariants", testPrimaryKeyColumnConstraintVariants),
        ("testPrimaryKeyTableConstraintVariants", testPrimaryKeyTableConstraintVariants),
        ("testRawQueryStringInterpolation", testRawQueryStringInterpolation),
        ("testTableConstraints", testTableConstraints),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SQLKitTests.__allTests__SQLKitTests),
    ]
}
#endif
